backend:
  name: github
  repo: gobeli/eleventy-preact
media_folder: static
collections:
  - name: pages
    label: Pages
    files:
      - label: 'Home Page'
        name: home
        file: src/content/home.md
        fields:
          - { label: Layout, name: layout, widget: hidden, default: home }
          - { label: Permalink, name: permalink, widget: hidden, default: index.html }
          - { label: Title, name: title, widget: string }
          - { label: Photo, name: logo, widget: image }
          - { label: Body, name: body, widget: markdown }
  - name: posts
    label: Posts
    folder: src/content/posts
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: Layout, name: layout, widget: hidden, default: post.11ty.tsx }
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: string }
      - { label: Date, name: date, widget: date }
      - { label: Body, name: body, widget: markdown }